---
settings:
  name: Astra Control Center
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '21.12'
    url: "/astra-control-center-2112"
  - version-number: '21.08'
    url: "/astra-control-center-2108"
  - version-number: '22.04'
    url: "/astra-control-center-2204"
  - version-number: '22.08'
    url: "/astra-control-center-2208"
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Control Center 21.12 - Dokumentation
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: get-started
  - section: use
  - section: rest-api
  - section: solutions
  - section: support
  - title: Frühere Versionen
    url: "/acc-earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
