---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes 
summary: Das Hinzufügen von Objektspeicher-Bucket-Providern ist äußerst wichtig, wenn Sie Applikationen und persistenten Storage sichern möchten, wenn Sie Applikationen über mehrere Cluster hinweg klonen möchten. 
---
= Buckets verwalten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Ein Objektspeicher-Bucket-Provider ist äußerst wichtig, wenn Sie Ihre Applikationen und Ihren persistenten Storage sichern möchten oder Applikationen über Cluster hinweg klonen möchten. Fügen Sie mithilfe des Astra Control Center einen Objektspeicher-Provider als externes Backup-Ziel für Ihre Applikationen hinzu.

Sie brauchen keinen Eimer, wenn Sie Ihre Anwendungskonfiguration und Ihren persistenten Storage im selben Cluster klonen.

Nutzen Sie einen der folgenden Bucket-Provider:

* NetApp ONTAP S3
* NetApp StorageGRID S3
* Allgemein S3



NOTE: Obwohl Astra Control Center Amazon S3 als Generic S3 Bucket-Provider unterstützt, unterstützt Astra Control Center möglicherweise nicht alle Objektspeicher-Anbieter, die die S3-Unterstützung von Amazon beanspruchen.

Ein Bucket kann nicht gelöscht werden, Sie können ihn jedoch bearbeiten.

Ein Bucket kann sich in einem dieser Zustände befinden:

* Ausstehend: Der Bucket ist für die Erkennung geplant.
* Verfügbar: Der Bucket ist zur Verwendung verfügbar.
* Entfernt: Auf den Bucket ist derzeit nicht zugegriffen werden können.


Anweisungen zum Verwalten von Buckets mithilfe der Astra Control API finden Sie im link:https://docs.netapp.com/us-en/astra-automation/["Astra Automation und API-Informationen"^].

Sie können die folgenden Aufgaben zum Verwalten von Buckets ausführen:

* link:../get-started/setup_overview.html#add-a-bucket["Fügen Sie einen Bucket hinzu"]
* <<Bearbeiten eines Buckets>>



NOTE: S3 Buckets im Astra Control Center berichten nicht über die verfügbare Kapazität. Bevor Sie Backups oder Klonanwendungen durchführen, die von Astra Control Center gemanagt werden, sollten Sie die Bucket-Informationen im ONTAP oder StorageGRID Managementsystem prüfen.



== Anmeldedaten entfernen

Entfernen Sie jederzeit S3-Anmeldeinformationen mithilfe der Astra Control API aus einem Konto.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/astra-automation/index.html["Verwenden Sie die Astra Control API"^].


TIP: Der erste Satz von Anmeldeinformationen, die Sie Astra Control hinzufügen, wird immer verwendet, da Astra Control zur Authentifizierung des Backup-Buckets die Zugangsdaten verwendet. Es ist am besten, diese Anmeldeinformationen nicht zu entfernen.



== Bearbeiten eines Buckets

Sie können die Zugangsdaten für einen Bucket ändern und ändern, ob ein ausgewählter Bucket der Standard-Bucket ist.


NOTE: Wenn Sie einen Bucket hinzufügen, wählen Sie den richtigen Bucket-Provider aus und geben die richtigen Anmeldedaten für diesen Provider an. Beispielsweise akzeptiert die UI NetApp ONTAP S3 als Typ und akzeptiert StorageGRID-Anmeldedaten. Dies führt jedoch dazu, dass alle künftigen Applikations-Backups und -Wiederherstellungen, die diesen Bucket verwenden, fehlschlagen. Siehe link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["Versionshinweise"].

.Schritte
. Wählen Sie in der linken Navigationsleiste *Buckets* aus.
. Wählen Sie im Menü Aktionen die Option *Bearbeiten*.
. Ändern Sie alle Informationen außer dem Bucket-Typ.
+

TIP: Sie können den Bucket-Typ nicht ändern.

. Wählen Sie *Aktualisieren*.




== Weitere Informationen

* https://docs.netapp.com/us-en/astra-automation/index.html["Verwenden Sie die Astra Control API"^]

