---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Hier wird beschrieben, wie Sie das Astra Control Center und den Astra Control Center Operator entfernen. 
---
= Deinstallieren Sie Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Möglicherweise müssen Sie die Komponenten des Astra Control Center entfernen, wenn Sie ein Upgrade von einer Testversion auf eine Vollversion des Produkts durchführen. Um Astra Control Center und den Astra Control Center Operator zu entfernen, führen Sie die in diesem Verfahren beschriebenen Befehle nacheinander aus.

.Was Sie benötigen
* Verwenden Sie die Benutzeroberfläche von Astra Control Center, um das Management aller zu lösen link:../use/unmanage.html#stop-managing-compute["Cluster"].


.Schritte
. Löschen Sie Das Astra Control Center. Der folgende Beispielbefehl basiert auf einer Standardinstallation. Ändern Sie den Befehl, wenn Sie benutzerdefinierte Konfigurationen erstellt haben.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Ergebnis:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Löschen Sie den mit dem folgenden Befehl `netapp-acc` Namespace:
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Ergebnis:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Löschen Sie die Komponenten des Astra Control Center-Bedienersystems mit dem folgenden Befehl:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Ergebnis:

+
[listing]
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----




== Weitere Informationen

* link:../release-notes/known-issues.html["Bekannte Probleme bei der Deinstallation"]

