---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters 
summary: 'Erste Schritte mit Astra Control Center: Überprüfen Sie die Unterstützung Ihrer Kubernetes Cluster, Applikationen und Webbrowser.' 
---
= Anforderungen des Astra Control Centers
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Prüfen Sie zunächst die Bereitschaft Ihrer Betriebsumgebung, Anwendungscluster, Applikationen, Lizenzen und Ihres Webbrowsers.



== Anforderungen an die Betriebsumgebung

Astra Control Center erfordert eine der folgenden Typen von Betriebsumgebungen:

* Red hat OpenShift Container Platform 4.6.8, 4.7 oder 4.8
* Rancher 2.5
* Kubernetes 1.19 bis 1.21 (einschließlich 1.21.x)


Stellen Sie sicher, dass die Betriebsumgebung, die Sie als Host für das Astra Control Center auswählen, den grundlegenden Ressourcenanforderungen in der offiziellen Dokumentation der Umgebung entspricht. Astra Control Center erfordert zusätzlich zu den Ressourcenanforderungen der Umgebung die folgenden Ressourcen:

|===
| Komponente | Anforderungen 


| Back-End ONTAP Storage-Kapazität | Mindestens 300 GB verfügbar 


| Worker-Nodes | Insgesamt mindestens 3 Worker-Nodes mit 4 CPU-Kernen und jeweils 12 GB RAM 


| Load Balancer | Der Servicetyp „loadbalancer“ ist für den Ingress Traffic verfügbar, der an Services im Cluster der Betriebsumgebung gesendet werden kann 


| FQDN-Auflösung | Eine Methode zum Zeigen des FQDN von Astra Control Center auf die Load Balanced IP-Adresse 


| Astra Trident  a| 
* Astra Trident 21.04 oder neuer ist installiert und konfiguriert, wenn NetApp ONTAP Version 9.5 oder höher als Storage-Backend verwendet wird
* Astra Trident 21.10.1 oder neuer ist installiert und konfiguriert, wenn die Astra Data Store-Vorschau als Storage-Backend verwendet wird


|===

NOTE: Bei diesen Anforderungen wird davon ausgegangen, dass Astra Control Center die einzige Applikation ist, die in der Betriebsumgebung ausgeführt wird. Wenn in der Umgebung zusätzliche Applikationen ausgeführt werden, passen Sie diese Mindestanforderungen entsprechend an.

* *Image Registry*: Sie benötigen eine bereits vorhandene private Docker-Image-Registry, mit der Sie Astra Control Center-Bilder erstellen können. Sie müssen die URL der Bildregistrierung angeben, in der Sie die Bilder hochladen.
* *Astra Trident / ONTAP Konfiguration*: Astra Control Center erfordert, dass eine Storage-Klasse erstellt und als Standard-Storage-Klasse eingestellt wird. Astra Control Center unterstützt die folgenden ONTAP-Treiber von Astra Trident:
+
** ontap-nas
** ontap-san
** ontap-san-Ökonomie




[NOTE]
====
Beim Klonen von Applikationen in OpenShift-Umgebungen muss das Astra Control Center OpenShift erlauben, Volumes anzuhängen und die Eigentümerschaft von Dateien zu ändern. Daher müssen Sie eine ONTAP Volume Export-Richtlinie konfigurieren, damit diese Vorgänge möglich sind. Sie können dies mit folgenden Befehlen tun:

. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -superuser sys`
. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -anon 65534`


====

NOTE: Wenn Sie eine zweite OpenShift-Betriebsumgebung als gemanagte Computing-Ressource hinzufügen möchten, müssen Sie sicherstellen, dass die Astra Trident Volume Snapshot-Funktion aktiviert ist. Um Volume Snapshots mit Astra Trident zu aktivieren und zu testen, https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["Sehen Sie sich die offiziellen Anweisungen von Astra Trident an"^].



== Anforderungen für Applikationscluster

Astra Control Center hat folgende Anforderungen für Cluster, die Sie über das Astra Control Center verwalten möchten. Diese Anforderungen gelten auch, wenn der zu verwaltende Cluster der Betriebsumgebung ist, der das Astra Control Center hostet.

* Die neueste Version von Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html["snapshot-Controller-Komponente"^] Installiert ist
* Astra Trident https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["Objekt der Volumesnapshotklasse"^] Wurde von einem Administrator definiert
* Im Cluster ist eine standardmäßige Kubernetes-Storage-Klasse vorhanden
* Mindestens eine Storage-Klasse ist für die Verwendung von Astra Trident konfiguriert



NOTE: Ihr Applikations-Cluster sollte einen haben `kubeconfig.yaml` Datei, die nur ein _context_ -Element definiert. In der Kubernetes-Dokumentation für finden Sie https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Informationen zum Erstellen von kubeconfig-Dateien"^].


NOTE: Wenn Sie Anwendungscluster in einer Rancher-Umgebung verwalten, ändern Sie den Standardkontext des Anwendungsclusters im `kubeconfig` Die von Rancher bereitgestellte Datei verwendet anstelle des Rancher API-Serverkontexts einen Steuerebenen-Kontext. So wird die Last auf dem Rancher API Server reduziert und die Performance verbessert.



== Anforderungen für das Applikationsmanagement

Astra Control verfügt über folgende Anforderungen an das Applikationsmanagement:

* *Lizenzierung*: Zur Verwaltung von Anwendungen mit dem Astra Control Center benötigen Sie eine Astra Control Center-Lizenz.
* *Namesaces*: Astra Control erfordert, dass eine App nicht mehr als einen Single Namespace umfasst, aber ein Namespace kann mehr als eine App enthalten.
* *StorageClass*: Wenn Sie eine Anwendung mit einem explizit eingestellten StorageClass installieren und die App klonen müssen, muss das Zielcluster für den Klonvorgang die ursprünglich angegebene StorageClass haben. Das Klonen einer Applikation, deren StorageClass explizit auf ein Cluster festgelegt ist, das nicht über dieselbe StorageClass verfügt, schlägt fehl.
* *Kubernetes-Ressourcen*: Applikationen, die nicht mit Astra Control gesammelte Kubernetes-Ressourcen verwenden, verfügen unter Umständen nicht über umfassende Funktionen zum App-Datenmanagement. Astra Control sammelt die folgenden Kubernetes-Ressourcen:
+
** ClusterCole
** ClusterrollenBding
** Konfigmap
** KundenressourcenDefinition
** Benutzerressource
** DemonSet
** Einsatz
** BereitstellungConfig
** Eindringen
** MutatingWebhook
** PersistentVolumeClaim
** Pod
** ReplicaSet
** Rollenverschwarten
** Rolle
** Route
** Geheim
** Service
** Service Account
** StatfulSet
** ValidierenWebhook






=== Unterstützte Installationsmethoden für Anwendungen

Astra Control unterstützt folgende Installationsmethoden für Anwendungen:

* *Manifest-Datei*: Astra Control unterstützt Apps, die aus einer Manifest-Datei mit kubectl installiert wurden. Beispiel:
+
[listing]
----
kubectl apply -f myapp.yaml
----
* *Helm 3*: Wenn Sie Helm zur Installation von Apps verwenden, benötigt Astra Control Helm Version 3. Das Management und Klonen von Apps, die mit Helm 3 installiert sind (oder ein Upgrade von Helm 2 auf Helm 3), wird vollständig unterstützt. Das Verwalten von mit Helm 2 installierten Apps wird nicht unterstützt.
* *Vom Betreiber bereitgestellte Apps*: Astra Control unterstützt Apps, die mit Betreibern mit Namespace-Scoped installiert sind. Im Folgenden sind einige Apps aufgeführt, die für dieses Installationsmodell validiert wurden:
+
** https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
** https://github.com/jenkinsci/kubernetes-operator["Jenkins CI"^]
** https://github.com/percona/percona-xtradb-cluster-operator["Percona XtraDB Cluster"^]





NOTE: Ein Operator und die von ihm zu installieren App müssen denselben Namespace verwenden. Möglicherweise müssen Sie die yaml-Bereitstellungsdatei ändern, um sicherzustellen, dass dies der Fall ist.



== Zugang zum Internet

Sie sollten feststellen, ob Sie einen externen Zugang zum Internet haben. Wenn nicht, sind einige Funktionen möglicherweise begrenzt, beispielsweise das Empfangen von Monitoring- und Kennzahlendaten von NetApp Cloud Insights oder das Senden von Support-Paketen an die https://mysupport.netapp.com/site/["NetApp Support Website"^].



== Lizenz

Astra Control Center erfordert eine Astra Control Center-Lizenz für die volle Funktionalität. Anfordern einer Evaluierungslizenz oder Volllizenz von NetApp. Ohne Lizenz können Sie Folgendes nicht ausführen:

* Definieren benutzerdefinierter Applikationen
* Snapshots oder Klone vorhandener Applikationen erstellen
* Konfigurieren von Datensicherungsrichtlinien


Wenn Sie das Astra Control Center ausprobieren möchten, können Sie das auch link:setup_overview.html#add-a-full-or-evaluation-license["Verwenden Sie eine 90-Tage-Evaluierungslizenz"].



== Servicetyp „Load Balancer“ für lokale Kubernetes-Cluster

Astra Control Center verwendet einen Service des Typs "loadbalancer" (svc/Traefik im Astra Control Center Namespace) und erfordert, dass ihm eine zugängliche externe IP-Adresse zugewiesen wird. Wenn in Ihrer Umgebung Load Balancer zulässig sind und noch nicht bereits eine konfiguriert ist, können Sie verwenden https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["MetalLB"^] So weisen Sie dem Dienst automatisch eine externe IP-Adresse zu. In der Konfiguration des internen DNS-Servers sollten Sie den ausgewählten DNS-Namen für Astra Control Center auf die Load-Balanced IP-Adresse verweisen.



== Netzwerkanforderungen

Die Betriebsumgebung, die als Host für Astra Control Center fungiert, kommuniziert über die folgenden TCP-Ports. Sie sollten sicherstellen, dass diese Ports über beliebige Firewalls zugelassen sind, und Firewalls so konfigurieren, dass jeder HTTPS-ausgehenden Datenverkehr aus dem Astra-Netzwerk zugelassen wird. Einige Ports erfordern Verbindungen zwischen der Umgebung, in der Astra Control Center gehostet wird, und jedem verwalteten Cluster (sofern zutreffend).

|===
| Quelle | Ziel | Port | Protokoll | Zweck 


| Client-PC | Astra Control Center | 443 | HTTPS | UI/API-Zugriff - Stellen Sie sicher, dass dieser Port auf beiden Wegen zwischen dem Cluster geöffnet ist, der Astra Control Center hostet, und jedem verwalteten Cluster 


| Kennzahlenverbraucher | Astra Control Center Worker-Node | 9090 | HTTPS | Kennzahlen Datenkommunikation - sicherstellen, dass jeder verwaltete Cluster auf diesen Port auf dem Cluster zugreifen kann, das Astra Control Center hostet (Kommunikation in zwei Bereichen erforderlich) 


| Astra Control Center | Gehosteter Cloud Insights Service  | 443 | HTTPS | Cloud Insights Kommunikation 


| Astra Control Center | Amazon S3 Storage-Bucket-Provider  | 443 | HTTPS | Amazon S3 Storage-Kommunikation 


| Astra Control Center | NetApp Active IQ  | 443 | HTTPS | NetApp Active IQ Kommunikation 
|===


== Unterstützte Webbrowser

Astra Control Center unterstützt aktuelle Versionen von Firefox, Safari und Chrome mit einer Mindestauflösung von 1280 x 720.



== Wie es weiter geht

Sehen Sie sich die an link:quick-start.html["Schnellstart"] Überblick.
